services:
  web:
    build: . # <-- ¡Esta es la línea que cambia!
    container_name: portalconcretol_web
    volumes:
      - .:/var/www/html
    environment:
      - VIRTUAL_HOST=portalconcretol.local
    networks:
      - web-proxy
    restart: unless-stopped

networks:
  web-proxy:
    external: true
